db:
  # 数据库服务器地址端口
  hostname: localhost
  port: 5432

  # 数据库用户名密码
  username: postgres
  password: 123456

  # 数据库名
  db-name: postgres
  ssl-mode: disable

jwt:
  # jwt密钥
  secret-key: mySecret

  # jwt有效期
  expires-duration: 240h

server:
  listen-ip: 0.0.0.0
  listen-port: 8080